const MOVIE_DATA = 'MOVIE_DATA';
const TV_DATA = 'TV_DATA';

const CLEAR_MOVIE_DATA = 'CLEAR_MOVIE_DATA';
const CLEAR_TV_DATA = 'CLEAR_TV_DATA';
const CLEAR_TV_IMAGES = 'CLEAR_TV_IMAGES';
const CLEAR_SEARCH = 'CLEAR_SEARCH';

const UPCOMING_MOVIES = 'UPCOMING_MOVIES';
const TOP_MOVIES = 'TOP_MOVIES';
const POPULAR_MOVIES = 'POPULAR_MOVIES';
const PLAYING_MOVIES = 'PLAYING_MOVIES';

export const AIRING_TV = 'AIRING_TV';
export const TOP_TV = 'TOP_TV';
export const POPULAR_TV = 'POPULAR_TV';
export const ON_THE_AIR_TV = 'ON_THE_AIR_TV';


const SEARCH_VALUE = 'SEARCH_VALUE';
const SEARCH_MOVIE = 'SEARCH_MOVIE';


export { MOVIE_DATA, CLEAR_MOVIE_DATA, UPCOMING_MOVIES, POPULAR_MOVIES, PLAYING_MOVIES, SEARCH_VALUE, SEARCH_MOVIE, CLEAR_SEARCH, TOP_MOVIES, TV_DATA, CLEAR_TV_DATA, CLEAR_TV_IMAGES };
