const UPCOMING_MOVIES = 'UPCOMING_MOVIES';
const TOP_MOVIES = 'TOP_MOVIES';
const POPULAR_MOVIES = 'POPULAR_MOVIES';
const PLAYING_MOVIES = 'PLAYING_MOVIES';
const SEARCH_VALUE = 'SEARCH_VALUE';
const SEARCH_MOVIE = 'SEARCH_MOVIE';


export { UPCOMING_MOVIES, POPULAR_MOVIES, PLAYING_MOVIES, SEARCH_VALUE, SEARCH_MOVIE, TOP_MOVIES };
