const MOVIE_DATA = 'MOVIE_DATA';
const TV_DATA = 'TV_DATA';

const CLEAR_MOVIE_DATA = 'CLEAR_MOVIE_DATA';
const CLEAR_TV_DATA = 'CLEAR_TV_DATA';
const CLEAR_SEARCH = 'CLEAR_SEARCH';

const UPCOMING_MOVIES = 'UPCOMING_MOVIES';
const TOP_MOVIES = 'TOP_MOVIES';
const POPULAR_MOVIES = 'POPULAR_MOVIES';
const PLAYING_MOVIES = 'PLAYING_MOVIES';

const SEARCH_VALUE = 'SEARCH_VALUE';
const SEARCH_MOVIE = 'SEARCH_MOVIE';


export { MOVIE_DATA, CLEAR_MOVIE_DATA, UPCOMING_MOVIES, POPULAR_MOVIES, PLAYING_MOVIES, SEARCH_VALUE, SEARCH_MOVIE, TOP_MOVIES, TV_DATA, CLEAR_TV_DATA,CLEAR_SEARCH };
